---
wrapper:
  base_url: "file:///home/hermidalc/projects/github/hermidalc/snakemake-wrappers/"

samples: "config/samples.tsv"
units: "config/units.tsv"

gencode:
  protocol: "ftp"
  species: "mouse"
  release: "M30"
  build: "GRCm39"
  regions: "PRI"
  annot:
    fmt: "gtf"

fastq:
  prefix_wildcard_str: "{unit}"
  pairs: ["R1_001", "R2_001"]
  platform: "Illumina"

trimming:
  activate: true
  threads: 8

star:
  index:
    threads: 32
  align:
    sort_bam: true
    threads: 32
