---
wrapper:
  base_url: "file:///home/hermidalc/projects/github/hermidalc/snakemake-wrappers/"

tmp_dir: "/tmp"

random_seed: 777

download:
  retries: 5

study:
  name: "light_vs_light_dye"
  samples: "config/samples.tsv"
  units: "config/units.tsv"

gencode:
  protocol: "ftp"
  species: "mouse"
  release: "M30"
  build: "GRCm39"
  regions: "PRI"
  annot:
    fmt: "gtf"
  gene_annot:
    length_col: "Length"

fastq:
  data_dir: "data/fastq"
  pairs: ["R1_001", "R2_001"]
  ext: "fastq.gz"
  platform: "Illumina"

trim:
  activate: true
  fastp:
    threads: 8
    extra_params: "--trim_poly_x --detect_adapter_for_pe --correction"

star:
  index:
    threads: all
  align:
    sort_bam: true
    threads: all
  # regex specific to GTF style
  sj_filter_chr_regex: "^(?!chrM$).+$"  # "chr([1-9][0-9]?|X|Y)"

rseqc:
  infer_exp:
    sample_size: 1e6

diffexp:
  methods: ["edger"]
  experiments: ["mitoFAP"]
  contrast: ["light", "light_dye"]
  contrast_label: ["light", "light+dye"]
  has_batches: false
  qc_types: ["rle", "pca", "mds"]
  qc_legend: "topright"
  rle_ylim: [-2, 2]
  fc: 1.1
  padj: 0.05
  padj_meth: BH
