---
wrapper:
  base_url: "file:///home/hermidalc/projects/github/hermidalc/snakemake-wrappers/"

study:
  name: "R10_pEtn"
  samples: "config/samples.tsv"
  units: "config/units.tsv"

gencode:
  protocol: "ftp"
  species: "mouse"
  release: "M30"
  build: "GRCm39"
  regions: "PRI"
  annot:
    fmt: "gtf"

fastq:
  pairs: ["R1_001", "R2_001"]
  platform: "Illumina"

trimming:
  activate: true
  threads: 8

star:
  index:
    threads: 16
  align:
    sort_bam: true
    threads: 16

rseqc:
  infer_exp:
    sample_size: 1000000
