---
wrapper:
  base_url: "https://github.com/hermidalc/snakemake-wrappers/raw"

gencode:
  species: "mouse"
  version: "M30"
  build: "GRCm39"

trimming:
  activate: true
  dirname: trimmed
  threads: 8

star:
  index:
    threads: 32
  align:
    threads: 32
