---
wrapper:
  base_url: "file:///home/hermidalc/projects/github/hermidalc/snakemake-wrappers/"

tmp_dir: "/tmp"

download:
  retries: 5

study:
  name: "study"
  samples: "config/samples.tsv"
  units: "config/units.tsv"

gencode:
  protocol: "ftp"
  species: "mouse"
  release: "M30"
  build: "GRCm39"
  regions: "PRI"
  annot:
    fmt: "gtf"
  gene_annot:
    length_col: "Length"

fastq:
  data_dir: "data/fastq"
  pairs: ["R1_001", "R2_001"]
  ext: "fastq.gz"
  platform: "Illumina"

trimming:
  activate: true
  fastp:
    threads: 8
    extra_params: "--trim_poly_x --detect_adapter_for_pe --correction"

star:
  index:
    threads: 16
  align:
    sort_bam: true
    threads: 16
  # regex specific to GTF style
  sj_filter_chr_regex: "^(?!chrM$).+$"  # "chr([1-9][0-9]?|X|Y)"

rseqc:
  infer_exp:
    sample_size: 1e6
